services:
  db:
    image: postgres:15
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app_development -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
      build:
        context: .
        dockerfile: Dockerfile.dev
      tty: true
      stdin_open: true
      volumes:
        - .:/app
        - bundle_data:/usr/local/bundle:cached
      ports:
        - "3000:3000"
      depends_on:
        db:
          condition: service_healthy
      command: >
        bash -c "
          bundle install &&
          bundle exec rails db:prepare &&
          rm -f tmp/pids/server.pid &&
          bundle exec rails server -b 0.0.0.0
        "
volumes:
  postgres_data:
  bundle_data: